export const cartActionTypes = {
  TOGGLE_CART_DROPDOWN: "TOGGLE_CART_DROPDOWN",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  DECREMENT_QUANTITY: "DECREMENT_QUANTITY",
  CLEAR_CART: "CLEAR_CART",
  SET_CART_FROM_FIREBASE: "SET_CART_FROM_FIREBASE",
  UPDATE_CART_IN_FIREBASE: "UPDATE_CART_IN_FIREBASE"
};
