export const userActionTypes = {
  GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",
  GOOGLE_SIGN_IN_SUCCESS: "GOOGLE_SIGN_IN_SUCCESS",
  GOOGLE_SIGN_IN_FAILURE: "GOOGLE_SIGN_IN_FAILURE",
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  EMAIL_SIGN_IN_SUCCESS: "EMAIL_SIGN_IN_SUCCESS",
  EMAIL_SIGN_IN_FAILURE: "EMAIL_SIGN_IN_FAILURE",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  CHECK_USER_SESSION_SUCCESS: "CHECK_USER_SESSION_SUCCESS",
  CHECK_USER_SESSION_FAILURE: "CHECK_USER_SESSION_FAILURE",
  SIGN_USER_OUT_START: "SIGN_USER_OUT_START",
  SIGN_USER_OUT_SUCCESS: "SIGN_USER_OUT_SUCCESS",
  SIGN_USER_OUT_FAILURE: "SIGN_USER_OUT_FAILURE"
};
